# Generated by Django 6.0.2 on 2026-03-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_autor_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ManyToManyField(related_name='livros', to='biblioteca.autor'),
        ),
    ]
